version: "3.7"
services:
  app:
    build:
      context: .
    container_name: app
    image: app:latest
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - ${BASE_PORT:-8000}:8000
    depends_on:
      - postgres
#      - redis
#
#  workerHighPriority:
#    container_name: high-priority-worker
#    image: web:latest
#    command: ["workerHighPriority"]
#    env_file:
#      - .env
#    volumes:
#      - .:/usr/src/app
#    depends_on: *deps


  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    command: -p ${DATABASE_PORT:-5432}
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-postgres}
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
    ports:
      - ${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}
    volumes:
      - postgres:/var/lib/postgresql

#  redis:
#    container_name: redis
#    image: redis:5-alpine
#    command: --port ${REDIS_PORT:-6379}
#    ports:
#      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}

volumes:
  postgres:
