[tool.black]
line-length = 120
include = '\.pyi?$'
force-exclude = '''
/(
    | venv/*
    | templates/
    | data/
    | media/
    | test-media/
)/
'''

[tool.isort]
profile = "black"
extend_skip = "settings, templates"
