# Generated by Django 4.1.6 on 2023-03-09 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hash",
                    models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.BigIntegerField(editable=False, unique=True)),
                ("parent_hash", models.CharField(editable=False, max_length=128, null=True, unique=True)),
                ("extrinsic_data", models.JSONField(default=dict)),
                ("event_data", models.JSONField(default=dict)),
                ("executed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
            },
        ),
        migrations.CreateModel(
            name="Dao",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, null=True)),
                ("metadata_url", models.CharField(max_length=256, null=True)),
                ("metadata_hash", models.CharField(max_length=256, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="daos", to="core.account"
                    ),
                ),
            ],
            options={
                "verbose_name": "DAO",
                "verbose_name_plural": "DAOs",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("total_supply", models.PositiveBigIntegerField()),
                (
                    "dao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="asset", to="core.dao"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="core.account"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.CreateModel(
            name="AssetHolding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.PositiveBigIntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="holdings", to="core.asset"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="holdings", to="core.account"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Holding",
                "verbose_name_plural": "Asset Holdings",
                "db_table": "core_asset_holding",
                "unique_together": {("asset", "owner")},
            },
        ),
    ]
