# Generated by Django 4.1.6 on 2023-02-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("total_supply", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hash",
                    models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True),
                ),
                ("number", models.BigIntegerField(editable=False, unique=True)),
                ("parent_hash", models.CharField(editable=False, max_length=128, null=True, unique=True)),
                ("extrinsic_data", models.JSONField(default=dict)),
                ("event_data", models.JSONField(default=dict)),
                ("executed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dao",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.account")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetHolding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.IntegerField()),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.asset")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.account")),
            ],
            options={
                "db_table": "core_asset_holding",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="dao",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.dao"),
        ),
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.account"),
        ),
    ]
