# Generated by Django 4.1.7 on 2023-03-23 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("metadata", models.JSONField(null=True)),
                ("metadata_url", models.CharField(max_length=256, null=True)),
                ("metadata_hash", models.CharField(max_length=256, null=True)),
                (
                    "dao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="proposals", to="core.dao"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Governance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(choices=[("MAJORITY_VOTE", "majority vote")], max_length=128)),
                ("proposal_duration", models.IntegerField()),
                ("proposal_token_deposit", models.IntegerField()),
                ("minimum_majority", models.IntegerField()),
                (
                    "dao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="governance", to="core.dao"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
