# Generated by Django 4.1.7 on 2023-03-28 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_create_challenge"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Challenge",
        ),
    ]
