# Generated by Django 4.1.7 on 2023-04-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_delete_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="dao",
            name="creator",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_daos", to="core.account"
            ),
        ),
        migrations.AddField(
            model_name="dao",
            name="setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dao",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owned_daos", to="core.account"
            ),
        ),
    ]
