# Generated by Django 4.1.7 on 2023-04-18 08:43

import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_dao_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="total_supply",
            field=core.utils.BiggerIntField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="assetholding",
            name="balance",
            field=core.utils.BiggerIntField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="governance",
            name="proposal_token_deposit",
            field=core.utils.BiggerIntField(max_length=1024),
        ),
    ]
