# Generated by Django 4.1.7 on 2023-04-18 08:43

import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_create_bigger_int_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("in_favor", models.BooleanField(null=True)),
                ("voting_power", core.utils.BiggerIntField(max_length=1024)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.proposal"
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.account"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
