# Generated by Django 4.1.7 on 2023-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_create_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "in progress"),
                    ("ACCEPTED", "accepted"),
                    ("REJECTED", "rejected"),
                    ("FAULTED", "faulted"),
                ],
                default="IN_PROGRESS",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="reason_for_fault",
            field=models.TextField(null=True),
        ),
    ]
