# Generated by Django 4.1.7 on 2023-04-25 11:45

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_index_to_vote_in_favor"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="ends_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "running"),
                    ("PENDING", "pending"),
                    ("REJECTED", "rejected"),
                    ("IMPLEMENTED", "implemented"),
                    ("FAULTED", "faulted"),
                ],
                default=core.models.ProposalStatus["RUNNING"],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="creator",
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.SET_NULL, related_name="proposals", to="core.account"
            ),
        ),
    ]
