# Generated by Django 4.1.7 on 2023-04-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_proposal_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.proposal")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="reason_for_fault",
            new_name="fault",
        ),
    ]
