# Generated by Django 4.1.7 on 2023-05-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_proposal_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="ends_at",
        ),
        migrations.AddField(
            model_name="proposal",
            name="birth_block_number",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
