# Generated by Django 4.1.7 on 2023-07-05 14:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_proposal_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiSignature",
            fields=[
                (
                    "account_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.account",
                    ),
                ),
                (
                    "signatories",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None),
                ),
                ("threshold", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("core.account",),
        ),
    ]
