# Generated by Django 4.1.7 on 2023-06-27 07:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_proposal_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiSignature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=250), blank=True, size=None
                    ),
                ),
                ("threshold", models.IntegerField()),
                (
                    "dao",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daos", to="core.dao"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
