# Generated by Django 4.1.7 on 2023-06-29 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_multisignature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multisignature",
            old_name="signers",
            new_name="signatories",
        ),
    ]
