# Generated by Django 4.1.7 on 2023-06-29 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_signers_multisignature_signatories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multisignature",
            old_name="dao",
            new_name="dao_id",
        ),
    ]
