# Generated by Django 4.1.7 on 2023-08-17 17:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_proposal_setup_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiSig",
            fields=[
                (
                    "account_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.account",
                    ),
                ),
                (
                    "signatories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), default=list, size=None
                    ),
                ),
                ("threshold", models.PositiveIntegerField(null=True)),
                ("dao", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.dao")),
            ],
            options={
                "verbose_name": "MultiSig Account",
                "verbose_name_plural": " MultiSig Accounts",
            },
            bases=("core.account",),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("call", models.JSONField(null=True)),
                ("call_hash", models.CharField(max_length=256)),
                (
                    "approvers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), default=list, size=None
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("APPROVED", "approved"),
                            ("CANCELLED", "cancelled"),
                            ("EXECUTED", "executed"),
                        ],
                        default=core.models.TransactionStatus["PENDING"],
                        max_length=16,
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_by", models.CharField(max_length=256, null=True)),
                (
                    "dao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.dao",
                    ),
                ),
                (
                    "multisig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="core.multisig"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "unique_together": {("call_hash", "multisig", "executed_at")},
            },
        ),
        migrations.DeleteModel(
            name="MultiSignature",
        ),
    ]
