# Generated by Django 4.1.7 on 2023-08-21 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="core.asset"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="proposal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="core.proposal"
            ),
        ),
    ]
