# Generated by Django 4.1.7 on 2023-06-29 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_rename_dao_multisignature_dao_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multisignature",
            old_name="dao_id",
            new_name="dao",
        ),
    ]
