# Generated by Django 4.1.7 on 2023-07-03 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_rename_dao_id_multisignature_dao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multisignature",
            name="dao",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.dao"),
        ),
    ]
