# Generated by Django 4.1.7 on 2023-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_transaction_add_asset_and_proposal_fks"),
    ]

    operations = [
        # django misses these for some reason...
        migrations.RunSQL(
            sql="""
                drop index if exists core_proposalreport_proposal_id_b80c9925_like;
                drop index if exists core_transaction_proposal_id_4cd721ea_like;
                drop index if exists core_vote_proposal_id_d5e686c6_like;
            """
        ),
        migrations.AlterField(
            model_name="proposal",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="proposalreport",
            table="core_proposal_report",
        ),
        migrations.RenameModel(
            old_name="Transaction",
            new_name="MultiSigTransaction",
        ),
        migrations.AlterModelOptions(
            name="multisigtransaction",
            options={"verbose_name": "MultiSigTransaction", "verbose_name_plural": "MultiSigTransactions"},
        ),
        migrations.AlterModelTable(
            name="multisigtransaction",
            table="core_multisig_transactions",
        ),
    ]
