# Generated by Django 4.1.7 on 2023-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_multisigtransaction_call_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="multisigtransaction",
            name="timepoint",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
