# Generated by Django 4.1.7 on 2023-09-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_multisigtransaction_timepoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multisigtransaction",
            name="timepoint",
            field=models.JSONField(null=True),
        ),
    ]
