# Generated by Django 4.1.7 on 2023-09-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_multisigtransaction_timepoint_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multisigtransaction",
            name="call_data",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
