# Generated by Django 4.1.7 on 2023-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_multisigtransaction_call_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="multisigtransaction",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="multisigtransaction",
            constraint=models.UniqueConstraint(
                fields=("call_hash", "multisig", "executed_at"), name="unique_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="multisigtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("executed_at", None)),
                fields=("call_hash", "multisig"),
                name="unique_without_optional",
            ),
        ),
    ]
