# Generated by Django 4.1.7 on 2023-11-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_fix_multisig_transaction_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetholding",
            name="delegated_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delegated_holdings",
                to="core.account",
            ),
        ),
    ]
