# Generated by Django 4.1.7 on 2023-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_asset_holding_add_delegated_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="dao",
            name="ink_asset_contract",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dao",
            name="ink_registry_contract",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dao",
            name="ink_vesting_wallet_contract",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="dao",
            name="ink_vote_escrow_contract",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
