# Generated by Django 4.1.7 on 2023-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_dao_ink_asset_contract_dao_ink_registry_contract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetholding",
            name="vesting_wallet",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="assetholding",
            name="vote_escrow",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
